FROM python:3.10.14-alpine
ENV PYTHONUNBUFFERED=1

WORKDIR /app/

COPY . /app/


RUN pip3 install --upgrade pip


RUN pip3 install -r requirements.txt

#0.0.0.0:8000 is required as it allows traffic from outside the container.

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
